version: 2

jobs:
  build:
    working_directory: ~/ring-headers-formatter
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      LC_ALL: C
    steps:
      - checkout
      - restore_cache:
          key: ring-headers-formatter-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: ring-headers-formatter-{{ checksum "project.clj" }}
      - run: lein test
      - run: lein cloverage --fail-threshold 95
      - run: lein kibit
      - run: lein eastwood
